### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by slashinfty** [mmtrt/legendsofruneterra#12]
Running Arch Linux. When it downloads and runs live.exe, I get this every time:

![2022-03-16_16-41](https://user-images.githubusercontent.com/14860235/158687158-940d7fa6-ba3e-4a4a-97fb-1eb391635e5a.png)
.

**Comment by mmtrt** [comment]
Current installer is broken atm anyways I've fixed it locally will push changes.

**Comment by slashinfty** [comment]
Looking forward to hopefully installing it. I'm not alone: https://www.reddit.com/r/leagueoflinux/comments/tdb48j/update_server_down/

**Comment by mmtrt** [comment]
@slashinfty it should work now.

**Comment by slashinfty** [comment]
It has! Thank you for the fix.
