### ISSUE TITLE
Not high enough permissions for mounting temporary files

### ISSUE THREAD

**Issue by MantoStar** [mmtrt/legendsofruneterra#18]
Hello,
I have recently stumbled upon a problem when trying to boot up the game.
For some reason, the app lacks permissions when trying to mount a temporary file system, putting out this message:
`cannot perform operation: mount -t tmpfs /tmp/snap.rootfs_3xlRjj: Permission denied`
I am not sure what caused that sudden change, as I have not manually changed any permissions for that directory.
Probably some update, as I am on openSUSE Tumbleweed.
I have already tried a fresh install to no avail, so do you have any more suggestions regarding this?

**Comment by mmtrt** [comment]
that could be a `snapd` issue anyways can you post `snap list`

**Comment by MantoStar** [comment]
Here you go.
![image](https://github.com/mmtrt/legendsofruneterra/assets/125097998/9b9b3e94-4777-4190-8a05-5430af7f4456)

**Comment by mmtrt** [comment]
that seems fine, I guess try removing all snaps and snapd, resetup all.

**Comment by MantoStar** [comment]
Alright, it works now! Thank you again!
