### ISSUE TITLE
Snap stopped working.

### ISSUE THREAD

**Issue by colonnezi** [mmtrt/legendsofruneterra#19]
Since 15 or 20 days the game's not running anymore.
The terminal tells me this:
0410:err:rpc:I_RpcGetBuffer no binding

**Comment by colonnezi** [comment]
Solved itself (?)

**Comment by colonnezi** [comment]
Happening again.

tito@jarvis-v6x:~$ snap run legendsofruneterra
0224:err:rpc:I_RpcGetBuffer no binding

**Comment by colonnezi** [comment]
should i try to update something?

**Comment by mmtrt** [comment]
no updates atm, will try to update it when I get free time.

**Comment by colonnezi** [comment]
> no updates atm, will try to update it when I get free time.

is there anything to do with current league issue?

**Comment by colonnezi** [comment]
solved itself (again)
