### ISSUE TITLE
Service Error, code 060100

### ISSUE THREAD

**Issue by colonnezi** [mmtrt/legendsofruneterra#21]
I've tried to launch the game today. The game updated (after some re-launching) but i can't log in. Getting "service error", with the code above.

**Comment by mmtrt** [comment]
test snap from beta branch see if that fixes anything.

**Comment by colonnezi** [comment]
how do i update to beta branch? snap refresh is not working

**Comment by mmtrt** [comment]
`snap refresh --beta legendsofruneterra`

**Comment by colonnezi** [comment]
`tito@jarvis-v6x:~$ snap run legendsofruneterra
/snap/legendsofruneterra/18/bin/sommelier: line 497: notify-send: command not found
wineserver: using server-side synchronization.
002c:err:seh:install_bpf Unexpected status 0xffffffff, errno 9.
0034:err:seh:install_bpf Unexpected status 0xffffffff, errno 9.
0040:err:seh:install_bpf Unexpected status 0xffffffff, errno 9.
005c:err:seh:install_bpf Unexpected status 0xffffffff, errno 9.
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
0074:err:seh:install_bpf Unexpected status 0xffffffff, errno 9.
0084:err:plugplay:enumerate_new_device Unable to install a function driver for device L"WINEBUS\\VID_845E&PID_0001\\0&0000&0&0".
007c:err:wineusb:DriverEntry Failed to initialize Unix library, status 0xc0000135.
007c:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000135
0084:err:plugplay:enumerate_new_device Unable to install a function driver for device L"WINEBUS\\VID_845E&PID_0002\\0&0000&0&0".
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
00a0:err:seh:install_bpf Unexpected status 0xffffffff, errno 9.
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
00a0:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
00a0:err:winediag:nodrv_CreateWindow L"The explorer process failed to start."
00a0:err:systray:initialize_systray Could not create tray window
00b4:err:seh:install_bpf Unexpected status 0xffffffff, errno 9.
0024:err:seh:install_bpf Unexpected status 0xffffffff, errno 21.
0024:err:module:import_dll Library win32u.dll (which is needed by L"C:\\windows\\system32\\user32.dll") not found
0024:err:module:import_dll Library user32.dll (which is needed by L"C:\\windows\\system32\\gdi32.dll") not found
0024:err:module:import_dll Library win32u.dll (which is needed by L"C:\\windows\\system32\\gdi32.dll") not found
0024:err:module:import_dll Library gdi32.dll (which is needed by L"C:\\windows\\system32\\comctl32.dll") not found
0024:err:module:import_dll Library win32u.dll (which is needed by L"C:\\windows\\system32\\user32.dll") not found
0024:err:module:import_dll Library user32.dll (which is needed by L"C:\\windows\\system32\\gdi32.dll") not found
0024:err:module:import_dll Library win32u.dll (which is needed by L"C:\\windows\\system32\\gdi32.dll") not found
0024:err:module:import_dll Library gdi32.dll (which is needed by L"C:\\windows\\system32\\imm32.dll") not found
0024:err:module:import_dll Library win32u.dll (which is needed by L"C:\\windows\\system32\\gdi32.dll") not found
0024:err:module:import_dll Library gdi32.dll (which is needed by L"C:\\windows\\system32\\user32.dll") not found
0024:err:module:import_dll Library win32u.dll (which is needed by L"C:\\windows\\system32\\user32.dll") not found
0024:err:module:import_dll Library user32.dll (which is needed by L"C:\\windows\\system32\\imm32.dll") not found
0024:err:module:import_dll Library win32u.dll (which is needed by L"C:\\windows\\system32\\imm32.dll") not found
0024:err:module:import_dll Library imm32.dll (which is needed by L"C:\\windows\\system32\\comctl32.dll") not found
0024:err:module:import_dll Library win32u.dll (which is needed by L"C:\\windows\\system32\\gdi32.dll") not found
0024:err:module:import_dll Library gdi32.dll (which is needed by L"C:\\windows\\system32\\user32.dll") not found
0024:err:module:import_dll Library win32u.dll (which is needed by L"C:\\windows\\system32\\user32.dll") not found
0024:err:module:import_dll Library user32.dll (which is needed by L"C:\\windows\\system32\\comctl32.dll") not found
0024:err:module:import_dll Library comctl32.dll (which is needed by L"C:\\windows\\system32\\aclui.dll") not found
0024:err:module:import_dll Library win32u.dll (which is needed by L"C:\\windows\\system32\\user32.dll") not found
0024:err:module:import_dll Library user32.dll (which is needed by L"C:\\windows\\system32\\gdi32.dll") not found
0024:err:module:import_dll Library win32u.dll (which is needed by L"C:\\windows\\system32\\gdi32.dll") not found
0024:err:module:import_dll Library gdi32.dll (which is needed by L"C:\\windows\\system32\\aclui.dll") not found
0024:err:module:import_dll Library win32u.dll (which is needed by L"C:\\windows\\system32\\gdi32.dll") not found
0024:err:module:import_dll Library gdi32.dll (which is needed by L"C:\\windows\\system32\\user32.dll") not found
0024:err:module:import_dll Library win32u.dll (which is needed by L"C:\\windows\\system32\\user32.dll") not found
0024:err:module:import_dll Library user32.dll (which is needed by L"C:\\windows\\system32\\aclui.dll") not found
0024:err:module:import_dll Library aclui.dll (which is needed by L"C:\\windows\\system32\\shell32.dll") not found
0024:err:module:import_dll Library win32u.dll (which is needed by L"C:\\windows\\system32\\user32.dll") not found
0024:err:module:import_dll Library user32.dll (which is needed by L"C:\\windows\\system32\\gdi32.dll") not found
0024:err:module:import_dll Library win32u.dll (which is needed by L"C:\\windows\\system32\\gdi32.dll") not found
0024:err:module:import_dll Library gdi32.dll (which is needed by L"C:\\windows\\system32\\shell32.dll") not found
0024:err:module:import_dll Library win32u.dll (which is needed by L"C:\\windows\\system32\\user32.dll") not found
0024:err:module:import_dll Library user32.dll (which is needed by L"C:\\windows\\system32\\gdi32.dll") not found
0024:err:module:import_dll Library win32u.dll (which is needed by L"C:\\windows\\system32\\gdi32.dll") not found
0024:err:module:import_dll Library gdi32.dll (which is needed by L"C:\\windows\\system32\\shlwapi.dll") not found
0024:err:module:import_dll Library win32u.dll (which is needed by L"C:\\windows\\system32\\gdi32.dll") not found
0024:err:module:import_dll Library gdi32.dll (which is needed by L"C:\\windows\\system32\\user32.dll") not found
0024:err:module:import_dll Library win32u.dll (which is needed by L"C:\\windows\\system32\\user32.dll") not found
0024:err:module:import_dll Library user32.dll (which is needed by L"C:\\windows\\system32\\shlwapi.dll") not found
0024:err:module:import_dll Library shlwapi.dll (which is needed by L"C:\\windows\\system32\\shell32.dll") not found
0024:err:module:import_dll Library win32u.dll (which is needed by L"C:\\windows\\system32\\gdi32.dll") not found
0024:err:module:import_dll Library gdi32.dll (which is needed by L"C:\\windows\\system32\\user32.dll") not found
0024:err:module:import_dll Library win32u.dll (which is needed by L"C:\\windows\\system32\\user32.dll") not found
0024:err:module:import_dll Library user32.dll (which is needed by L"C:\\windows\\system32\\shell32.dll") not found
0024:err:module:import_dll Library shell32.dll (which is needed by L"C:\\windows\\system32\\start.exe") not found
0024:err:module:import_dll Library win32u.dll (which is needed by L"C:\\windows\\system32\\gdi32.dll") not found
0024:err:module:import_dll Library gdi32.dll (which is needed by L"C:\\windows\\system32\\user32.dll") not found
0024:err:module:import_dll Library win32u.dll (which is needed by L"C:\\windows\\system32\\user32.dll") not found
0024:err:module:import_dll Library user32.dll (which is needed by L"C:\\windows\\system32\\start.exe") not found
0024:err:module:loader_init Importing dlls for L"C:\\windows\\system32\\start.exe" failed, status c0000135
`

**Comment by mmtrt** [comment]
delete `$HOME/snap/legendsofruneterra` and resetup game.
