### ISSUE TITLE
Missing Sound Devices

### ISSUE THREAD

**Issue by Garfield4** [mmtrt/legendsofruneterra#5]
Hi 

I can run the game but have no sound or devices showing in winecfg. 

legendsofruneterra.winecfg
ALSA lib conf.c:3710:(snd_config_hook_load) cannot stat file/directory /usr/share/alsa/cards/aliases.conf
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.default
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.default

I play league of legends and that installation uses winepulse.drv rather than winealsa.drv and works fine and shows all output options. 

Please help me fix it.

Many thanks

**Comment by mmtrt** [comment]
pushed changes can you try update snap thanks.

`snap refresh`

**Comment by Garfield4** [comment]
Hi

Thanks for the speedy response and all you do - that worked :)
